export const RESTAURANT_CATEGORIES = [
  "korean",
  "chinese",
  "japanese",
  "western",
  "bakery",
  "icecream",
  "cafe",
  "fastfood",
  "bunsik",
  "bar",
  "vietnamese",
  "thai",
  "indian",
  "meat",
  "udon",
  "tonkatsu",
  "sushi",
  "seafood",
  "soba",
  "shaved",
  "donut",
  "noodle",
  "pocha",
  "hof",
] as const;

export type RestaurantCategory = (typeof RESTAURANT_CATEGORIES)[number];
